USE COVID19
GO


TRUNCATE TABLE INTL.COUNTRY
DBCC CHECKIDENT ('INTL.COUNTRY', RESEED,0)

BEGIN TRANSACTION
INSERT INTO [COVID19].[INTL].[COUNTRY]
SELECT COUNTRY_REGION FROM DBO.[03-30-2020] WHERE COUNTRY_REGION <>'US' AND PROVINCE_STATE =''
  ORDER BY COUNTRY_REGION,PROVINCE_STATE ASC


SELECT * FROM [COVID19].[INTL].[COUNTRY]
COMMIT
