USE COVID19
GO
--CREATE SCHEMA INTL
--GO
IF OBJECT_ID('INTL.COUNTRY', 'U') IS NOT NULL
  DROP TABLE INTL.COUNTRY
GO
IF OBJECT_ID('INTL.PROVINCES', 'U') IS NOT NULL
  DROP TABLE INTL.PROVINCES
GO

CREATE TABLE INTL.COUNTRY(
COUNTRYID INT NOT NULL IDENTITY,CONSTRAINT PK_COUNTRIES PRIMARY KEY CLUSTERED (COUNTRYID),
COUNTRY_NM VARCHAR(100) NOT NULL
)

CREATE TABLE INTL.PROVINCES(
PROVINCEID INT NOT NULL IDENTITY,CONSTRAINT PK_PROVINCES PRIMARY KEY CLUSTERED (PROVINCEID),
PROVINCE_NM VARCHAR(100) NOT NULL,
COUNTRY_NM VARCHAR(100) NULL,
COUNTRYID INT NULL
)