USE COVID19
GO
--SELECT SUM(CURRENTCASES) FROM
(SELECT S.STATE_NM,MAX(U.CASES) CURRENTCASES,MAX(U.DEATHS) CURRENTDEATHS 
FROM DEV.US_STATES_TRACKING U JOIN DEV.STATES S ON S.STATEID=U.STATEID AND S.ISASTATE=1
GROUP BY S.STATE_NM)
ORDER BY S.STATE_NM ASC

--SELECT S.STATE_NM,u.CASES CURRENTCASES,u.DEATHS CURRENTDEATHS 
--FROM DEV.US_STATES_TRACKING U JOIN DEV.STATES S ON S.STATEID=U.STATEID AND S.ISASTATE=1
--WHERE S.STATE_NM='Virginia'
----GROUP BY S.STATE_NM
--ORDER BY S.STATE_NM ASC

--select * from [us-states] where state='Virginia'