USE COVID19
GO


TRUNCATE TABLE DEV.US_STATES_TRACKING
DBCC CHECKIDENT ('DEV.US_STATES_TRACKING', RESEED,0)

BEGIN TRANSACTION
INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='ALABAMA'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='ALASKA'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='ARIZONA'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='ARKANSAS'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='CALIFORNIA'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='COLORADO'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='CONNECTICUT'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='DELAWARE'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='DISTRICT OF COLUMBIA'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='FLORIDA'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='GEORGIA'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='GUAM'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='HAWAII'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='IDAHO'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='ILLINOIS'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='INDIANA'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='IOWA'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='KANSAS'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='KENTUCKY'


INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='LOUISIANA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='MAINE'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='MARYLAND'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='MASSACHUSETTS'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='MICHIGAN'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='MINNESOTA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='MISSISSIPPI'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='MISSOURI'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='MONTANA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='NEBRASKA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='NEVADA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='NEW HAMPSHIRE'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='NEW JERSEY'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='NEW MEXICO'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='NEW YORK'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='NORTH CAROLINA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='NORTH DAKOTA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='OHIO'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='OKLAHOMA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='OREGON'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='PENNSYLVANIA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='PUERTO RICO'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='RHODE ISLAND'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='SOUTH CAROLINA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='SOUTH DAKOTA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='TENNESSEE'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='TEXAS'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='UTAH'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='VERMONT'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='VIRGIN ISLANDS'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='VIRGINIA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='WASHINGTON'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='WEST VIRGINIA'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='WISCONSIN'

INSERT INTO DEV.US_STATES_TRACKING
(STATEID,DATE,FIPS,CASES,DEATHS)
SELECT ST.STATEID,NYTS.DATE, NYTS.FIPS,NYTS.CASES,NYTS.DEATHS FROM DBO.[US-STATES] NYTS
INNER JOIN DEV.STATES ST ON ST.STATE_NM=NYTS.STATE AND ST.STATE_NM='WYOMING'

SELECT * FROM DEV.US_STATES_TRACKING

--DBCC CHECKIDENT ('DEV.US_STATES_TRACKING', RESEED,0)
--ROLLBACK
COMMIT