USE COVID19
GO
TRUNCATE TABLE DEV.COUNTY
GO
DBCC CHECKIDENT ('DEV.COUNTY', RESEED,0)

BEGIN TRANSACTION
INSERT INTO DEV.COUNTY
(COUNTY_NM, STATE_NM) SELECT DISTINCT COUNTY,STATE FROM DBO.[US-COUNTIES] ORDER BY 1 ASC
SELECT * FROM DEV.COUNTY ORDER BY COUNTY_NM ASC
COMMIT

DECLARE @STATE VARCHAR(100)='ALABAMA'
BEGIN TRANSACTION
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE
SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Alaska'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE

SET @STATE='Arizona'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Arkansas'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='California'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Colorado'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Connecticut'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Delaware'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='District of Columbia'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Florida'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Georgia'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Guam'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Hawaii'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Idaho'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Illinois'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Indiana'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Iowa'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Kansas'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Kentucky'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Louisiana'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Maine'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Maryland'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Massachusetts'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Michigan'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Minnesota'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Mississippi'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Missouri'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Montana'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Nebraska'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Nevada'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='New Hampshire'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='New Jersey'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='New Mexico'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='New York'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='North Carolina'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='North Dakota'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Ohio'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Oklahoma'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Oregon'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Pennsylvania'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Puerto Rico'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Rhode Island'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='South Carolina'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='South Dakota'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Tennessee'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Texas'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Utah'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Vermont'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Virgin Islands'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Virginia'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Washington'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='West Virginia'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Wisconsin'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE
SET @STATE='Wyoming'
UPDATE DEV.COUNTY SET STATEID=(
	SELECT DISTINCT ST.STATEID
	FROM 
		DBO.[US-COUNTIES] USC,
		DEV.STATES ST
	WHERE 
		USC.STATE=ST.STATE_NM
		AND USC.STATE=@STATE
		AND ST.STATE_NM =@STATE) WHERE STATE_NM=@STATE

SELECT * FROM DEV.COUNTY WHERE STATE_NM=@STATE


COMMIT
--ROLLBACK
